services:
  db:
    container_name: tapfinder_db_container
    image: postgres:13  # Specify the version of PostgreSQL you want to use
    environment:
      POSTGRES_USER: user         # Replace with your desired username
      POSTGRES_PASSWORD: ilovebeer # Replace with your desired password
      POSTGRES_DB: tapfinder             # Replace with the name of the database you want to create
    volumes:
      - my_pgdata:/var/lib/postgresql/data  # Persist data in a volume
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Replace with your desired pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin           # Replace with your desired pgAdmin password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"  # Exposes pgAdmin web interface on port 5050
    networks:
      - mynetwork
    depends_on:
      - db
    

networks:
  mynetwork:
    driver: bridge

volumes:
  my_pgdata:
  pgadmin_data:
